### ISSUE TITLE
WPS 2.0 tests fail.

### ISSUE THREAD

**Issue by highsource** [highsource/ogc-schemas#100]
```
Testing [C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\tests\WPS\2.0/describeProcess_request.xml].
Error: Element [{http://www.opengis.net/wps/2.0.0}wps:DescribeProcess] is not known in this context and property does not allow DOM.
    at Object.Jsonix.Binding.Unmarshalls.Element.Jsonix.Class.unmarshalElement (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:1897:10)
    at Object.Jsonix.Binding.Unmarshaller.Jsonix.Class.unmarshalDocument (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2019:8)
    at C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2008:19
    at fs.js:266:14
    at Object.oncomplete (fs.js:107:15)
```

**Comment by highsource** [comment]
Fixed in #98.
