### ISSUE TITLE
Unable to create a WMTS marshaller

### ISSUE THREAD

**Issue by sampov2** [highsource/ogc-schemas#147]
I'm unable to create a WMTS 1.0 Capabilities document unmarshaller. Below is the code that creates problem. Relevant versions are ogc-schemas 2.5.2, jsonix 2.3.2, w3c-schemas 1.3.1.(W3C schemas were added because otherwise the jsonix context gives errors about xlink missing.

    var Jsonix = require('jsonix').Jsonix;
    var OWS_1_1_0 = require('ogc-schemas').OWS_1_1_0;
    var XLink_1_0 = require('w3c-schemas').XLink_1_0;
    var WMTS_1_0 = require('ogc-schemas').WMTS_1_0;
    
    var context =  new Jsonix.Context([WMTS_1_0, XLink_1_0, OWS_1_1_0]);
    var unmarshaller = context.createUnmarshaller();

.. and the error message I get is:

`
/home/v2/git/foo/node_modules/jsonix/jsonix.js:5857
						throw new Error('Type info [' + typeInfoName + '] is not known in this c
						      ^
Error: Type info [WMTS_1_0.LanguageStringType] is not known in this context.
    at Object.Jsonix.Context.Jsonix.Class.resolveTypeInfo (/home/v2/git/foo/node_modules/jsonix/jsonix.js:5857:13)
    at Object.Jsonix.Model.ElementPropertyInfo.Jsonix.Class.doBuild (/home/v2/git/foo/node_modules/jsonix/jsonix.js:3098:27)
    at Object.Jsonix.Model.PropertyInfo.Jsonix.Class.build (/home/v2/git/foo/node_modules/jsonix/jsonix.js:2770:9)
    at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (/home/v2/git/foo/node_modules/jsonix/jsonix.js:2205:20)
    at Object.Jsonix.Model.ClassInfo.Jsonix.Class.build (/home/v2/git/foo/node_modules/jsonix/jsonix.js:2199:25)
    at Object.Jsonix.Model.Module.Jsonix.Class.buildTypeInfos (/home/v2/git/foo/node_modules/jsonix/jsonix.js:3942:13)
    at Object.Jsonix.Context.Jsonix.Class.processModules (/home/v2/git/foo/node_modules/jsonix/jsonix.js:5816:13)
    at Object.Jsonix.Context.Jsonix.Class.initialize (/home/v2/git/foo/node_modules/jsonix/jsonix.js:5788:10)
    at Object.Class (/home/v2/git/foo/node_modules/jsonix/jsonix.js:44:19)
    at Object.<anonymous> (/home/v2/git/foo/server/test.js:8:16)
`

**Comment by highsource** [comment]
Here's the working test case for `WMTS_1_0`:

https://github.com/highsource/ogc-schemas/blob/master/scripts/tests/WMTS/1.0/WMTS_1_0.js

```javascript
var mappings = [XLink_1_0, OWS_1_1_0, GML_3_1_1, SMIL_2_0, SMIL_2_0_Language, WMTS_1_0];
```

**Comment by highsource** [comment]
Does it help?

**Comment by sampov2** [comment]
Never mind. The issue was the order in which the schemas are given to the context. It would be nice though that the order would not matter, but that is an issue with jsonix, not this project.

**Comment by sampov2** [comment]
Oh, and thanks for the help! I didn't notice your comments before I answered my own question..

**Comment by highsource** [comment]
Yes, see highsource/jsonix#50.
