### ISSUE TITLE
Some of the tests fail with Error: Illegal state: unexpected event type [4].

### ISSUE THREAD

**Issue by highsource** [highsource/ogc-schemas#64]
```
Error: Illegal state: unexpected event type [4].
   at Object.Jsonix.Model.ClassInfo.Jsonix.Class.unmarshal (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2156:14)
   at Object.Jsonix.Model.ElementPropertyInfo.Jsonix.Class.unmarshalElement (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2935:35)
   at Object.Jsonix.Model.AbstractElementsPropertyInfo.Jsonix.Class.unmarshal (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2831:9)
   at Object.Jsonix.Model.ClassInfo.Jsonix.Class.unmarshalProperty (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2175:8)
   at Object.Jsonix.Model.ClassInfo.Jsonix.Class.unmarshal (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2135:14)
   at Object.Jsonix.Model.AnyElementPropertyInfo.Jsonix.Class.unmarshalElement (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:3537:25)
   at Object.Jsonix.Model.AnyElementPropertyInfo.Jsonix.Class.unmarshal (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:3511:16)
   at Object.Jsonix.Model.ClassInfo.Jsonix.Class.unmarshalProperty (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2175:8)
   at Object.Jsonix.Model.ClassInfo.Jsonix.Class.unmarshal (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2142:14)
   at Object.Jsonix.Model.ElementPropertyInfo.Jsonix.Class.unmarshalElement (C:\Projects\workspaces\ogc-ng\ogc-schemas\scripts\node_modules\jsonix\jsonix.js:2935:35)
```

**Comment by highsource** [comment]
The problem was in the OM schema. See:

* http://stackoverflow.com/questions/29455790/does-a-complex-extending-xsanytype-allow-textual-content
* https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources-original/ogc/sweCommon/1.0.1/aggregateTypes.xsd#L141
* https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources-original/ogc/sweCommon/1.0.0/aggregateTypes.xsd#L142
* https://github.com/highsource/ogc-schemas/blob/master/schemas/src/main/resources-original/ogc/sweCommon/2.0/basic_types.xsd#L81

Fixed by patching schemas with `mixed="true"`
